import 'dotenv/config';
import { drizzle } from 'drizzle-orm/mysql2';
import { sql } from 'drizzle-orm';

const db = drizzle(process.env.DATABASE_URL);

const CATEGORIES = [
  { key: "aiDaily", slug: "ai-daily", nameZh: "AI 日报", nameEn: "AI Daily", descZh: "每日AI领域最重要的新闻和动态", descEn: "The most important AI news and updates daily", color: "#2563EB", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/category-ai-models-kyGgLUanPm3MYhCupMuTWD.webp", sortOrder: 1 },
  { key: "deepAnalysis", slug: "deep-analysis", nameZh: "深度解读", nameEn: "Deep Analysis", descZh: "AI技术与行业趋势的深度分析", descEn: "In-depth analysis of AI technology and industry trends", color: "#7C3AED", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/category-research-7gi5wUaTCLCRz56oefVqKY.webp", sortOrder: 2 },
  { key: "practicalGuide", slug: "practical-guide", nameZh: "实操指南", nameEn: "Practical Guide", descZh: "面向开发者的AI工具和技术实践", descEn: "AI tools and technical practices for developers", color: "#059669", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/category-devtools-fy4MJjSfjHrPDjL6kCqRP5.webp", sortOrder: 3 },
  { key: "industryInsights", slug: "industry-insights", nameZh: "行业洞察", nameEn: "Industry Insights", descZh: "AI行业商业动态与投资趋势", descEn: "AI industry business dynamics and investment trends", color: "#D97706", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/category-industry-NxWPfBL3NMp2yr7pDeVc7d.webp", sortOrder: 4 },
  { key: "caseStudy", slug: "case-study", nameZh: "案例研究", nameEn: "Case Study", descZh: "企业AI应用的真实案例与经验", descEn: "Real-world enterprise AI application cases and lessons", color: "#DC2626", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/category-investment-6Er2Equ7i4zLCZsSo49Scj.webp", sortOrder: 5 },
  { key: "opinion", slug: "opinion", nameZh: "观点", nameEn: "Opinion", descZh: "行业领袖和研究者的独立观点", descEn: "Independent perspectives from industry leaders and researchers", color: "#0891B2", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/category-policy-2KjDgUGUvcNtKgjudKcymG.webp", sortOrder: 6 },
];

const ARTICLES = [
  { categoryKey: "aiDaily", titleZh: "Claude 5 正式发布：首个通过完整图灵测试的AI模型", titleEn: "Claude 5 Officially Released: First AI Model to Pass Complete Turing Test", excerptZh: "Anthropic最新发布的Claude 5在复杂推理、代码生成和多模态理解方面取得了历史性突破，成为首个通过完整图灵测试的AI系统。", excerptEn: "Anthropic's latest Claude 5 achieves historic breakthroughs in complex reasoning, code generation, and multimodal understanding, becoming the first AI system to pass the complete Turing test.", contentZh: "Anthropic于2026年4月正式发布了Claude 5，这是人工智能发展史上的一个里程碑时刻。Claude 5不仅在所有主流基准测试中全面超越竞品，更成为首个通过完整图灵测试的AI系统。\n\n在技术层面，Claude 5采用了全新的混合架构，将Transformer与状态空间模型（SSM）深度融合，实现了在长序列推理上的质的飞跃。其上下文窗口扩展至200万token，同时推理速度提升了3倍。\n\n在安全性方面，Anthropic引入了名为Constitutional AI 3.0的新一代对齐框架，通过多层次的价值观校准机制，确保模型输出的可靠性和安全性。\n\n行业分析师认为，Claude 5的发布标志着AI行业进入了一个新的竞争阶段，将对OpenAI、Google DeepMind等竞争对手产生深远影响。", contentEn: "Anthropic officially released Claude 5 in April 2026, marking a milestone moment in the history of artificial intelligence. Claude 5 not only surpasses all competitors across mainstream benchmarks but also becomes the first AI system to pass the complete Turing test.\n\nTechnically, Claude 5 employs a novel hybrid architecture that deeply integrates Transformers with State Space Models (SSM), achieving a qualitative leap in long-sequence reasoning. Its context window extends to 2 million tokens while inference speed improves by 3x.\n\nOn the safety front, Anthropic introduced Constitutional AI 3.0, a next-generation alignment framework that ensures output reliability and safety through multi-layered value calibration mechanisms.\n\nIndustry analysts believe Claude 5's release marks a new competitive phase in the AI industry, with profound implications for competitors like OpenAI and Google DeepMind.", author: "Phrone AI Editorial", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/article-1-claude5-oF9875ruUnMXZfUFRbHrG5.webp", readTime: 12, views: 45200, featured: true, publishedAt: "2026-04-07" },
  { categoryKey: "industryInsights", titleZh: "OpenAI 估值突破3000亿美元：AI独角兽的商业化之路", titleEn: "OpenAI Valuation Surpasses $300B: The Commercialization Path of AI Unicorns", excerptZh: "随着GPT-5.4的发布和企业级API收入的爆发式增长，OpenAI的最新一轮融资估值达到3000亿美元。", excerptEn: "With the release of GPT-5.4 and explosive growth in enterprise API revenue, OpenAI's latest funding round reached a $300B valuation.", contentZh: "OpenAI在2026年第一季度完成了新一轮融资，估值达到3000亿美元，使其成为全球最有价值的私营科技公司之一。\n\nGPT-5.4的发布为OpenAI带来了前所未有的企业客户增长。据内部数据显示，企业级API收入在过去六个月内增长了400%，年化收入已突破200亿美元。\n\n值得关注的是，OpenAI正在从单纯的模型提供商转型为全栈AI平台。", contentEn: "OpenAI completed a new funding round in Q1 2026 at a $300 billion valuation, making it one of the most valuable private technology companies globally.\n\nThe release of GPT-5.4 brought unprecedented enterprise customer growth. Internal data shows enterprise API revenue grew 400% over the past six months, with annualized revenue exceeding $20 billion.\n\nNotably, OpenAI is transitioning from a pure model provider to a full-stack AI platform.", author: "Song Wei", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/article-2-openai-valuation-E39ffd7fy5GriQqN8YaRG4.webp", readTime: 8, views: 32100, featured: true, publishedAt: "2026-04-06" },
  { categoryKey: "deepAnalysis", titleZh: "Transformer之后：状态空间模型（SSM）的崛起与挑战", titleEn: "Beyond Transformers: The Rise and Challenges of State Space Models", excerptZh: "Mamba-3架构在长序列建模上展现出超越Transformer的潜力。", excerptEn: "The Mamba-3 architecture demonstrates potential to surpass Transformers in long-sequence modeling.", contentZh: "在过去七年中，Transformer架构一直是深度学习领域的主导范式。然而，随着Mamba-3等状态空间模型（SSM）的出现，这一格局正在发生变化。\n\nSSM的核心优势在于其线性时间复杂度。与Transformer的O(n²)注意力机制不同，SSM能够以O(n)的复杂度处理序列数据。\n\nMamba-3在多项基准测试中的表现令人瞩目：在长文档理解任务上，其准确率比同等规模的Transformer模型高出15%。", contentEn: "For the past seven years, the Transformer architecture has been the dominant paradigm in deep learning. However, with the emergence of State Space Models (SSMs) like Mamba-3, this landscape is changing.\n\nThe core advantage of SSMs lies in their linear time complexity. Unlike Transformer's O(n²) attention mechanism, SSMs can process sequential data at O(n) complexity.\n\nMamba-3's performance across multiple benchmarks is remarkable: on long document understanding tasks, its accuracy is 15% higher than Transformer models of equivalent scale.", author: "Dr. Chen Hao", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/article-3-ssm-transformers-4r2GDHVJb5KS3HLDxJnyWW.webp", readTime: 15, views: 18760, featured: true, publishedAt: "2026-04-05" },
  { categoryKey: "practicalGuide", titleZh: "2026年AI开发工具全景图：从IDE到部署的完整工具链", titleEn: "2026 AI Dev Tools Landscape: The Complete Toolchain from IDE to Deployment", excerptZh: "AI辅助编程工具已从代码补全进化到全栈开发。", excerptEn: "AI-assisted programming tools have evolved from code completion to full-stack development.", contentZh: "2026年，AI开发工具生态已经发生了翻天覆地的变化。Cursor 2.0引入了多文件编辑能力和项目级上下文理解。", contentEn: "In 2026, the AI development tools ecosystem has undergone a dramatic transformation. Cursor 2.0 introduced multi-file editing capabilities and project-level context understanding.", author: "Tech Review Team", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/article-4-devtools-VACyxggWweEQzNjCVBKML4.webp", readTime: 10, views: 29300, featured: false, publishedAt: "2026-04-04" },
  { categoryKey: "caseStudy", titleZh: "字节跳动如何用AI重构推荐系统：日活提升23%的幕后故事", titleEn: "How ByteDance Rebuilt Its Recommendation System with AI: The Story Behind 23% DAU Growth", excerptZh: "字节跳动在2025年底全面升级了TikTok和抖音的推荐算法。", excerptEn: "ByteDance comprehensively upgraded TikTok and Douyin's recommendation algorithms in late 2025.", contentZh: "字节跳动在2025年底启动了代号为\"Atlas\"的推荐系统重构项目。新系统的核心创新在于引入了一个基于LLM的语义理解层。", contentEn: "ByteDance launched the \"Atlas\" recommendation system overhaul project in late 2025. The core innovation of the new system lies in introducing an LLM-based semantic understanding layer.", author: "Industry Desk", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/article-5-bytedance-NWLiLwGdqPGvDz275p5WsV.webp", readTime: 14, views: 22800, featured: false, publishedAt: "2026-04-03" },
  { categoryKey: "opinion", titleZh: "AI安全不应成为创新的枷锁 — 一位研究者的反思", titleEn: "AI Safety Should Not Become a Shackle on Innovation — A Researcher's Reflection", excerptZh: "当前AI安全讨论中存在过度恐惧的倾向。", excerptEn: "There is a tendency toward excessive fear in current AI safety discussions.", contentZh: "作为一名从事AI安全研究超过十年的学者，我对当前AI安全讨论中的某些趋势感到担忧。", contentEn: "As a scholar who has been engaged in AI safety research for over a decade, I am concerned about certain trends in current AI safety discussions.", author: "Prof. Li Ming", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/article-6-ai-safety-LhotPsCLTUaLJjtpQff9sN.webp", readTime: 7, views: 15650, featured: false, publishedAt: "2026-04-02" },
  { categoryKey: "aiDaily", titleZh: "DeepSeek-V4：中文大模型的新王者", titleEn: "DeepSeek-V4: The New Champion of Chinese Language Models", excerptZh: "DeepSeek-V4在中文写作、代码生成和数学推理上全面超越竞品。", excerptEn: "DeepSeek-V4 surpasses competitors across Chinese writing, code generation, and mathematical reasoning.", contentZh: "DeepSeek-V4的发布在中文AI社区引起了巨大轰动。这款基于改进型MoE架构的大模型全面超越了国际竞品。", contentEn: "The release of DeepSeek-V4 has caused a sensation in the Chinese AI community. This large model based on an improved MoE architecture surpasses international competitors.", author: "Model Lab", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/article-7-deepseek-k6sgBzAaZybie3ggHqWgm5.webp", readTime: 11, views: 31500, featured: false, publishedAt: "2026-04-01" },
  { categoryKey: "industryInsights", titleZh: "AI Agent 元年：从概念到产品的关键转折", titleEn: "The Year of AI Agents: The Critical Shift from Concept to Product", excerptZh: "2026年被称为AI Agent元年。", excerptEn: "2026 is called the Year of AI Agents.", contentZh: "2026年被业界普遍称为\"AI Agent元年\"。Manus的推出标志着通用AI Agent的成熟。", contentEn: "2026 is widely regarded as the \"Year of AI Agents\" by the industry. The launch of Manus marked the maturation of general-purpose AI Agents.", author: "Phrone AI Editorial", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/article-8-ai-agents-gK62b98WxzSguksERVwzJf.webp", readTime: 13, views: 28900, featured: false, publishedAt: "2026-03-30" },
  { categoryKey: "deepAnalysis", titleZh: "Q1 2026 AI融资报告：全球AI投资达420亿美元创新高", titleEn: "Q1 2026 AI Funding Report: Global AI Investment Hits Record $42B", excerptZh: "2026年第一季度全球AI领域融资总额达到420亿美元。", excerptEn: "Global AI funding reached $42 billion in Q1 2026.", contentZh: "根据Phrone AI研究团队的统计，2026年第一季度全球AI领域的融资总额达到了创纪录的420亿美元。", contentEn: "According to the Phrone AI research team's statistics, global AI funding reached a record $42 billion in Q1 2026.", author: "Investment Research", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/article-9-funding-3GtHG4D52jw2UGWW59zJLk.webp", readTime: 9, views: 19800, featured: false, publishedAt: "2026-03-28" },
  { categoryKey: "practicalGuide", titleZh: "RAG 2.0 实战：构建企业级知识库的完整指南", titleEn: "RAG 2.0 in Practice: A Complete Guide to Building Enterprise Knowledge Bases", excerptZh: "检索增强生成（RAG）技术已进入2.0时代。", excerptEn: "Retrieval-Augmented Generation (RAG) has entered its 2.0 era.", contentZh: "RAG 2.0代表了检索增强生成技术的重大进化。", contentEn: "RAG 2.0 represents a major evolution in retrieval-augmented generation technology.", author: "Engineering Team", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/article-10-rag-KZUC3fCTnvnnEKC3eQEXYn.webp", readTime: 16, views: 24500, featured: false, publishedAt: "2026-03-26" },
  { categoryKey: "caseStudy", titleZh: "特斯拉FSD V13：完全自动驾驶的最后一公里", titleEn: "Tesla FSD V13: The Last Mile to Full Self-Driving", excerptZh: "特斯拉FSD V13在美国50个州获得监管批准。", excerptEn: "Tesla FSD V13 receives regulatory approval in all 50 US states.", contentZh: "特斯拉FSD V13的发布是自动驾驶行业的一个重要里程碑。", contentEn: "The release of Tesla FSD V13 is an important milestone in the autonomous driving industry.", author: "Auto Tech Desk", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/article-11-tesla-fsd-8sUpxMATGA2uSP9oshFggd.webp", readTime: 11, views: 35200, featured: false, publishedAt: "2026-03-24" },
  { categoryKey: "opinion", titleZh: "欧盟AI法案正式生效：企业合规指南与影响分析", titleEn: "EU AI Act Takes Effect: Enterprise Compliance Guide and Impact Analysis", excerptZh: "欧盟AI法案于2026年3月全面生效。", excerptEn: "The EU AI Act came into full effect in March 2026.", contentZh: "欧盟AI法案（EU AI Act）于2026年3月正式全面生效，成为全球首个综合性AI监管法律框架。", contentEn: "The EU AI Act came into full effect in March 2026, becoming the world's first comprehensive AI regulatory legal framework.", author: "Policy Desk", image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663513680832/5R6mPTYvg3rK42ihJNWm4d/article-12-eu-ai-act-JnjdKiziU2i9BtPesd2j4a.webp", readTime: 9, views: 17650, featured: false, publishedAt: "2026-03-22" },
];

async function seed() {
  console.log("Seeding categories...");
  for (const cat of CATEGORIES) {
    await db.execute(sql`INSERT INTO categories (\`key\`, slug, nameZh, nameEn, descZh, descEn, color, image, sortOrder)
      VALUES (${cat.key}, ${cat.slug}, ${cat.nameZh}, ${cat.nameEn}, ${cat.descZh}, ${cat.descEn}, ${cat.color}, ${cat.image}, ${cat.sortOrder})
      ON DUPLICATE KEY UPDATE nameZh=VALUES(nameZh), nameEn=VALUES(nameEn), descZh=VALUES(descZh), descEn=VALUES(descEn), color=VALUES(color), image=VALUES(image), sortOrder=VALUES(sortOrder)`);
    console.log(`  ✓ ${cat.key}`);
  }

  console.log("\nSeeding articles...");
  await db.execute(sql`DELETE FROM articles`);
  for (const art of ARTICLES) {
    await db.execute(sql`INSERT INTO articles (categoryKey, titleZh, titleEn, excerptZh, excerptEn, contentZh, contentEn, author, image, readTime, views, featured, published, publishedAt)
      VALUES (${art.categoryKey}, ${art.titleZh}, ${art.titleEn}, ${art.excerptZh}, ${art.excerptEn}, ${art.contentZh}, ${art.contentEn}, ${art.author}, ${art.image}, ${art.readTime}, ${art.views}, ${art.featured}, ${true}, ${art.publishedAt})`);
    console.log(`  ✓ ${art.titleEn.substring(0, 50)}...`);
  }

  console.log("\n✅ Seed complete!");
  process.exit(0);
}

seed().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
